### ISSUE TITLE
Erebus removes Forestry:fluid.milk block

### ISSUE THREAD

**Issue by felkami** [ganymedes01/TheErebus#689] opened 2019-02-17 03:28 UTC
Using Minecraft 1.12.2, Forge 14.23.5.2768

Installed mods:
CodeChickenLib-1.12.2-3.2.2.353-universal
forestry_1.12.2-5.8.1.322
jei_1.12.2-4.13.1.225
NotEnoughIDs-1.5.4.3
NotEnoughItems-1.12.2-2.4.2.240-universal

Installed the above mods, dumped all ID files using NEI, then added Erebus and dumped all ID files using NEI

Comparing the blocks dump, found that Forestry:fluid.milk is missing after install of Erebus.

Attempted to search Erebus-included dump file for Forestry milk and could not find it

Confirmed in NEI item lists that a milk fluid block exists without Erebus, but not with Erebus.

Couldn't find any other missing blocks, biomes, etc. Just milk... clearly bugs hate strong endoskeletons.

This is the entry for the missing block:
forestry:fluid.milk,272,TRUE,forestry.core.fluids.BlockForestryFluid,,,,,,,,,,,
[Without Erebus.zip](https://github.com/vadis365/TheErebus/files/2872631/Without.Erebus.zip)
[With Erebus.zip](https://github.com/vadis365/TheErebus/files/2872632/With.Erebus.zip)

**Comment by felkami** [comment] 2019-02-17 03:38
Forgot to state, this is the erebus version: Erebus-1.0.25

**Comment by vadis365** [comment] 2019-02-20 12:44
Hello,
Will look in to it. Thanks for the report.
Cheers,
Me.

**Comment by praecipitator** [comment] 2019-03-07 14:11
So that's where it's gone. I had Milk added as a fluid by (I think, not sure) Tinkers Construct. At some point it disappeared, and I couldn't drain it from the tank I had it in. The Milk Bucket (added by TConstruct) now shows the black-magenta texture.

And if I think back, the only relevant change I did was adding Erebus.

**Comment by vadis365** [comment] 2019-03-11 13:49
Hello,
Erebus implements the fluid milk, but doesn't use a block for it, I think what is happening is; the Erebus milk is regisered and other mods' milk are ignored, this means there is never a milk 'block'. Looks like the easiest way to handle the issue is to allow a config to turn off Erebus milk (and probably Honey) and then pack makers/players can choose what mods' milk replaces the Erebus things. It should all still be compat as we use the forge fluids system, so other mods' fluids will still work with Erebus things.
Will sort it out for the next update (tonight probably).
Cheers,
Me.

**Comment by vadis365** [comment] 2019-03-11 19:12
Hello,
OK well this is not an issue so it seems.
I just loaded up Forestry and Erebus and yeah Forestry milk is gone - but milk still works fine - I mean Erebus uses the correct forge fluid adding and capabilities. I can add milk to the Biogas Engine fine including from Erebus Bambuckets. Unless something is crashing or causing an issue here, I don't see a problem. Forestry even lets you disable their milk if needed in a config.
Going to close this for now because it seems a moot issue.
Cheers,
Me.

**Closed as completed by vadis365** 2019-03-11 19:12 UTC
Labels: tweak

**Comment by felkami** [comment] 2019-03-19 11:20
Without a milk block, you can't 'dump' the milk into the world.

**Comment by praecipitator** [comment] 2019-03-24 17:41
So, is there an option to disable Erebus milk now? I didn't find it...

Edit: weird behaviour: I have a milk block in singleplayer, but not on my server? What am I doing wrong?

**Comment by praecipitator** [comment] 2019-03-29 16:01
I found the reason why this happens in another mod's github. This indeed is not a bug on Erebus's side.

It seems like Forge keeps a list of fluids in the level.dat. If you install a new mod, and it overrides one of these fluids, you get this behavior.

What you need to do is shut down your server, open the level.dat in NBTExplorer, go to forge/DefaultFluidList, and then either remove tconstruct:milk or replace it with erebus:milk.
