### ISSUE TITLE
Wand of Animation Animated Block Mobs changing to Smooth Stone.

### ISSUE THREAD

**Issue by Hyperion505** [ganymedes01/TheErebus#652] opened 2018-09-21 01:33 UTC
Mainly through learning of PO2, the Wand of Animation seemed really fun to try out, but sadly when i use it and capture a Animated Block mob via Industrial Foregoing Mob  Imprisonment Tool then place it in a spawner, i get regular smooth stone Animated Blocks.

Playing this on Modern Sky Block 3 Departed If that has any merit to the issue.

**Comment by wamc2017** [comment] 2018-09-21 03:42
That's not a bug, Industrial Foregoing doesn't allow to spawn an exact copy by default. If you want this cheaty behavior, turn enableExactCopy on in IFs config, then a button in the spawner gui should appear which allows exact copys...

**Comment by vadis365** [comment] 2018-09-21 11:52
Closing because this is all good :)

**Closed as completed by vadis365** 2018-09-21 11:52 UTC

**Comment by Hyperion505** [comment] 2018-09-24 20:48
Sadly the "exact copy" option still just spawned in Stone

**Comment by wamc2017** [comment] 2018-09-24 22:35
Works fine in my testworld, so don't know what's wrong on your side...
![2018-09-25_00 33 40](https://user-images.githubusercontent.com/33242447/45982844-b0c39f00-c05a-11e8-9798-705ecbe590ef.png)

Did you click the button in the duplicator?
