### ISSUE TITLE
Cant launch Erebus 03a

### ISSUE THREAD

**Issue by Dream-Master** [ganymedes01/TheErebus#332] opened 2015-09-05 21:07 UTC
Cant launch with Erebus 0.3a and Forge 1492. It says it need Version 1448.

**Comment by Dream-Master** [comment] 2015-09-05 21:48
https://github.com/ganymedes01/TheErebus/commit/b90253c365ee61a85e283c0582928d14756adbe0

If fixed it using your last commit and compiling a new Version.

**Comment by Zsashas** [comment] 2015-09-15 06:56
How would I download the working version?

**Comment by Dream-Master** [comment] 2015-09-15 08:29
@Zsashas 
So you have the same problem ?
Send me an email and i give you a dropbox link of this Version.
dream-master@gmx.net

**Comment by vadis365** [comment] 2015-09-15 13:25
It works fine - I compiled and tested it. No one else has reported not being able to use it.
I have also watched a youtube play-through using this version.
It is a problem with your forge version no doubt.
I would rather you didn't distribute un-official non-release versions compiled from the github as there will be things in the mod which may be work in progress and unsupported if you report a crash.
The back dating of the forge version in the SRC was an experiment to see if it also runs on older versions. This will be changed back to the recommended forge version.
I am closing this issue because distribution of WIP mods compiled from the SRC will make it impossible for us to bug track. I have no issues with people compiling and using the mod for their own personal use - but please do not distribute it to other people as it is not an official release and any bugs reported will need a log. If that log does not contain the recommended version of forge it will be ignored.

**Closed by vadis365** 2015-09-15 13:25 UTC

**Comment by vadis365** [comment] 2015-09-15 13:45
*Post Script.
I will now have to release a new version with a different version number this week.
Bug tracking will be impossible if many people are using an unofficial version due to this.
Although your intentions are honorable  @Dream-Master they are a bit counter productive. ;)

**Comment by Dream-Master** [comment] 2015-09-15 15:27
I have the same problem with CoFH Core too. So all Versions need Forge 1448 i cant use in my Modpack with my Forge Version 1492. I cant find the error but i guess some mod make the problem. I only change the dependencies of Forge version so it isn't a real change in the Mod if you mean the licence thing. I only want to help out. But if you uploading a new this would be help too. Thanks

**Comment by Zsashas** [comment] 2015-09-15 15:52
In my case, I can't update Forge past 1400 without it constantly crashing, I have no idea why. Which also means no updated CoFH mods.

**Comment by Dream-Master** [comment] 2015-09-15 16:00
Screenshoot from your modpack will helping (folder) or Modpack list.

**Comment by Zsashas** [comment] 2015-09-15 16:08
Starting off by saying I don't know 100% how this works, but shouldn't it be simple enough to have to downloads, with the ONLY difference being the required Forge version?

**Comment by Dream-Master** [comment] 2015-09-15 16:12
I can only help if i know more about your pack.

**Comment by Zsashas** [comment] 2015-09-15 16:28
https://gyazo.com/edc656353ee76f1d96961418a5968154
https://gyazo.com/3eb584c4d345ea99666a95ca398f392b
https://gyazo.com/3ef59830133811a8717767553bcb7459
https://gyazo.com/4742a8f3f04ffa40ce32bc1c9fa679d3
https://gyazo.com/749fd35a1bb9b82c28c9f9fcf95d6e58
https://gyazo.com/784f213dc8d968bdcd9aaae65dd42411
https://gyazo.com/c32e1be4e60dfa4a05118543f5599f31

**Comment by Dream-Master** [comment] 2015-09-15 16:55
need time to investigate this because it is a big pack.

**Comment by vadis365** [comment] 2015-09-15 17:09
Post a crash report to pastebin it will tell you what the problem is from the stacktrace.

**Comment by Dream-Master** [comment] 2015-09-15 17:12
@vadis365 
If i send you my fml log you can see which mod cause the error with the Forge 1448 dependencies?

**Comment by vadis365** [comment] 2015-09-15 17:12
yes. that is what it is for.

**Comment by vadis365** [comment] 2015-09-15 17:22
@Zsashas
https://gyazo.com/784f213dc8d968bdcd9aaae65dd42411

That says you are running Erebus 0.2b - update to the latest recommended forge and use Erebus 0.3a then send me the latest FML log report please. There is no way of knowing what is causing you problems from looking at your mods folder.

**Comment by Zsashas** [comment] 2015-09-15 17:36
That screenshot was taken after downgrading back to 0.2.

**Comment by Zsashas** [comment] 2015-09-15 18:01
For reasons I don't understand, my pack is now seemingly working with both Forge 1448 and Erebus 0.3, when this was very much not the case before. Unfortunately I am unable to find one of those logs or crash reports.

**Comment by Zsashas** [comment] 2015-09-15 18:02
Also I just noticed that the original issue here was that he was using a version that was NEWER than the required, which should have still worked. My issue was using an older version and being unable to update.

**Comment by vadis365** [comment] 2015-09-15 18:05
I still can't do ANYTHING without  log files or crash reports.
@Zsashas - I'm glad it all works for you now :)

**Comment by Zsashas** [comment] 2015-09-15 18:07
![erebustest](https://cloud.githubusercontent.com/assets/6917535/9885421/f57a807e-5b99-11e5-890f-302bec61b67a.png)

Made a new world, seems to be working. Also, Marshwood textures are all funky.

**Comment by vadis365** [comment] 2015-09-15 18:08
Turn of alternative plank textures in the config file - marshwood doesn't have alternatives yet...

**Comment by vadis365** [comment] 2015-09-15 18:20
Locking this conversation as it is deviating from the original issue @Dream-Master please open a new issue and post your log if you are still having problems,

**Comment by ganymedes01** [comment] 2015-09-23 19:36
I got a report about a similar issue on one of my mods.
This appears to be a Cauldron bug breaking the Forge's version check somehow. Remove Cauldron and everything runs as it should.
