### ISSUE TITLE
[1.12.2] Bucket Bugs

### ISSUE THREAD

**Issue by NotAVerb** [ganymedes01/TheErebus#575] opened 2018-02-22 05:19 UTC
~Beetle juice and milk bambuckets are consumed upon use if there is only a single bucket in the stack, and no empty buckets in the inventory, and the inventory is full.~
~Beetle juice iron buckets simply can't be used.~ (cannot be drunk from but can contain fluids)
~Beetle juice fails to kill attached bot fly larva.~
~Beetles don't seem to be milkable with iron buckets.~

~Betweenlands weedwood and syrmorite buckets have beetle juice bucket items that can't be used nor created via milking.~ (not this mods issue really, they can contain the fluid and be used with tanks)

**Comment by vadis365** [comment] 2018-02-23 23:12
working my way though quite a few bits - most of above is fixed - leaving open as other issues here are still present atm.

**Comment by vadis365** [comment] 2018-02-24 22:48
Closing for now as this should mostly be working as intended in the 1.0.20 update.

**Closed as completed by vadis365** 2018-02-24 22:48 UTC
Labels: bug
