### ISSUE TITLE
Bamboo Crate Right Arrow broken

### ISSUE THREAD

**Issue by Zsashas** [ganymedes01/TheErebus#437] opened 2015-11-29 03:42 UTC
The left arrow works fine for scrolling the 3 pages, but the right arrow does nothing.

**Comment by vadis365** [comment] 2015-11-29 22:25
I'm using the same version and it works fine for me.

**Comment by Zsashas** [comment] 2015-11-29 22:26
I noticed the arrow didn't work for the last few versions, either. Only the left arrow has ever worked.

**Comment by ganymedes01** [comment] 2015-11-29 22:58
The buttons are probably not being positioned properly for some GUI scales

**Comment by vadis365** [comment] 2015-12-29 23:03
I tried on all gui scales in my workspace and both arrows worked fine  - is this fixed now?

**Comment by Darkosto** [comment] 2016-01-04 22:00
Can confirm, the arrow on the right hand side does not work. This is on a GUI Scale of Medium

**Comment by Zsashas** [comment] 2016-01-04 22:04
I always use the Auto scale, which is equal to Medium with my resolution.

**Comment by vadis365** [comment] 2016-01-06 14:01
Are you using inventory tweaks?
If so it may be to do with that as I don't have an issue. Please test without inv tweaks (if using).
It may be to do with the fact we search for inv tweaks' mod name and move our button. From what I could understand from glancing at inv tweaks' code there is no mod name string set just a mod ID.
I may be wrong - but that could be the cause.

**Comment by vadis365** [comment] 2016-01-30 18:25
Closing this issue due to lack of response and the fact I think it is inventory tweaks' problem.
When running The Erebus without it I have no issues.

**Closed by vadis365** 2016-01-30 18:25 UTC
