### ISSUE TITLE
Erebus mod forge issue

### ISSUE THREAD

**Issue by Jeffrey123454** [ganymedes01/TheErebus#544] opened 2016-07-07 09:09 UTC
so when i try to play erebus (i have other mods installed too) it says i need a higher version than 1291,i need 1566,but when i try it with a slightly newer version,1541 it crashes,i guess i need to try the 1566 one,but iam not sure if its an issue,bug or just plain stupidity of me...for those who curious,here is the crash report
[crash-2016-07-07_10.55.53-client.txt](https://github.com/ganymedes01/TheErebus/files/351758/crash-2016-07-07_10.55.53-client.txt)

EDIT: i just now installed the 1614 version,and still crashes,again,here is the crash report
[crash-2016-07-07_11.17.54-client.txt](https://github.com/ganymedes01/TheErebus/files/351774/crash-2016-07-07_11.17.54-client.txt)
P.S iam experiencing problems with every forge above 1300,and the same crash gets reported

**Comment by vadis365** [comment] 2016-07-07 17:16
Hello,
I can't really make out anything from the crash report.
I would suggest removing mods until you find which one is causing the crash.
The version of Erebus you have is the latest and it does require a forge of 1566 or above (of which you have). Also try to remove Optifine and see if that is the cause.
Cheers,
Me.

**Comment by vadis365** [comment] 2017-06-26 14:52
Closing - been nearly a year

**Closed as completed by vadis365** 2017-06-26 14:52 UTC
