### ISSUE TITLE
Continually teleporting back to the erebus

### ISSUE THREAD

**Issue by SilverKytten** [ganymedes01/TheErebus#623] opened 2018-06-12 06:16 UTC
I'm testing out my [modpack](https://www.technicpack.net/modpack/run-with-nature---test.925077/mods) and went to the erebus to make sure nothing was broken. 

I went back through the portal and was in the overworld for a few seconds before being teleported straight back to the erebus. This happens every time, even after breaking part of the portal blocks as well as the keystone.

**Comment by vadis365** [comment] 2018-06-15 10:58
Hello,
The Erebus portal will teleport you instantly with no cool down if you are in creative. I suspect that may be the cause if you are testing things out. If it's happening without a portal then, yeah, something is wrong in your pack, but I cannot duplicate this bug at all in any of my tests using just Erebus.
Cheers,
Me.

**Comment by vadis365** [comment] 2018-07-25 16:30
Is Stellar API in your pack? If so it could be related to this bug which is now fixed at their end.
https://github.com/Abastro/StellarAPI/issues/10
If that is the case, please update and close this issue if it's the cause
Cheers,
Me.

**Comment by vadis365** [comment] 2018-08-21 11:46
Closing due to no reply and not enough info to go on.

**Closed as completed by vadis365** 2018-08-21 11:46 UTC
