### ISSUE TITLE
Insect Repellent - improvements

### ISSUE THREAD

**Issue by DylanGK** [ganymedes01/TheErebus#705] opened 2019-03-18 15:17 UTC
Insect Repellent produces a rather annoying sound when pathing of arthropods sends them over it. The AI does not seem to recognise it as a block that cannot be passed. Is there some way in which we could make it so that only bug-type mobs regard this block as ''impassable terrain'' and their pathfinding then corrects their pathing to avoid this block?

I'd at least want the sound issue to be addressed, since mobs trying to path over it make a lot of noise that completely disincentives players to use it.

**Comment by vadis365** [comment] 2019-03-24 21:48
Block works as intended - but yeah the sound is annoying as all hell - will remove the sound :)
Fixed in dev.

**Closed as completed by vadis365** 2019-03-24 21:48 UTC
Labels: tweak
