### ISSUE TITLE
Preserved amber crash

### ISSUE THREAD

**Issue by TheJN101** [ganymedes01/TheErebus#631] opened 2018-07-22 09:49 UTC
i collected some mobs with your preserved amber feature, now i wanted to move them for estetic reasons and whenever one of those blocks is placed the game crashes. when i reenter everything is fine and the block is placed

**Comment by vadis365** [comment] 2018-07-25 16:35
Hello,
Could you please post a pastebin link to your crashlog? - that way I can see what is going on.
Cheers,
Me.

**Comment by TheJN101** [comment] 2018-07-25 16:49
Problem is i get no Crash log i Place a preserved ember and no matter if modded creature or vanilla the game freezes and logs back in on the server page but I played singleplayer.
Also it only happens after a while on a new world everything is fine for a while.
Hope my english was alright,
Cheers
Me
(If you could use help for german translation I would be glad to help one of my favorite mods)


Von meinem iPhone gesendet

**Comment by vadis365** [comment] 2018-07-25 17:15
Hello,
If you could pastebin the forge logs it may help - I mean I can't really do much without some information on the cause.
Cheers,
Me.

**Comment by TheJN101** [comment] 2018-08-08 17:55
This would be the last log i placed a preserved amber containing a donky
earlyer i tested if the mob was the cause but that doesn´t matter.
also removed some mods to test if they were the cause and readded them kif
it still happened.
i hope you can find the problem

Thx JN


Am Mi., 25. Juli 2018 um 19:15 Uhr schrieb vadis365 <
notifications@github.com>:

**Comment by vadis365** [comment] 2018-08-21 11:56
Closing, please make a new issue with some sort of crash log or forge log if this issue happens again.

**Closed as completed by vadis365** 2018-08-21 11:56 UTC
