### ISSUE TITLE
Exception getting block type in world

### ISSUE THREAD

**Issue by BunnyCinnamon** [ganymedes01/TheErebus#523] opened 2016-06-13 15:37 UTC
**Error 1:**
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/11/16 4:11 AM
Description: Exception getting block type in world

java.lang.RuntimeException: Already decorating Erebus!
    at erebus.world.biomes.decorators.BiomeDecoratorBaseErebus.decorate(BiomeDecoratorBaseErebus.java:37)
    at erebus.world.biomes.BiomeBaseErebus.func_76728_a(BiomeBaseErebus.java:111)
    at erebus.world.ChunkProviderErebus.func_73153_a(ChunkProviderErebus.java:399)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1201)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
    at net.minecraft.world.World.func_72964_e(World.java:796)
    at net.minecraft.world.World.func_147439_a(World.java:699)
    at net.minecraft.world.chunk.Chunk.func_76594_o(Chunk.java:1502)
    at net.minecraft.world.World.func_147467_a(World.java:3580)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:470)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at erebus.world.biomes.decorators.BiomeDecoratorBaseErebus.decorate(BiomeDecoratorBaseErebus.java:37)
    at erebus.world.biomes.BiomeBaseErebus.func_76728_a(BiomeBaseErebus.java:111)
    at erebus.world.ChunkProviderErebus.func_73153_a(ChunkProviderErebus.java:399)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1201)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
    at net.minecraft.world.World.func_72964_e(World.java:796)

-- Requested block coordinates --
Details:
    Found chunk: true
    Location: World: (-2561,24,-1360), Chunk: (at 15,1,0 in -161,-85; contains blocks -2576,0,-1360 to -2561,255,-1345), Region: (-6,-3; contains chunks -192,-96 to -161,-65, blocks -3072,0,-1536 to -2561,255,-1025)
Stacktrace:
    at net.minecraft.world.World.func_147439_a(World.java:699)
    at net.minecraft.world.chunk.Chunk.func_76594_o(Chunk.java:1502)
    at net.minecraft.world.World.func_147467_a(World.java:3580)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:470)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)

-- Affected level --
Details:
    Level name: DIM66
    All players: 1 total; [EntityPlayerMP['Naomi_Fujioka'/267739, l='DIM66', x=-2438.80, y=67.00, z=-1457.29](Naomi_Fujioka at -2438.7991070852368,67.0,-1457.286162036816)]
    Chunk stats: ServerChunkCache: 331 Drop: 0
    Level seed: 1420428394
    Level generator: ID 04 - RTG, ver 0. Features enabled: true
    Level generator options: RTG
    Level spawn location: World: (7,72,3), Chunk: (at 7,4,3 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 7608614 game time, 7787044 day time
    Level dimension: 66
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Thermos Version: ca.tcpr:Thermos:1.7.10-1614.56
    Plugins: DynamicIcon, WorldEdit, Playtime, Essentials, VoidWorld, ClearLag, WorldBorder, AlmostFlatLands, WorldGuard, Multiverse-Core, mcore, rpgParties, EssentialsProtect, EssentialsChat, PermissionsEx, Multiverse-Portals, Vault, EssentialsSpawn, GriefPrevention, ItemRestrict, MobArena, WorldClaim, Factions
    Disabled Plugins:
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1061604576 bytes (1012 MB) / 4205838336 bytes (4011 MB) up to 4205838336 bytes (4011 MB)
    JVM Flags: 3 total; -Xmx4096M -Xms4096M -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 1, tcache: 18, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 109 mods loaded, 109 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar)
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](custom256.jar)
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](custom256.jar)
    UCHIJAAAA   kimagine{0.2} [KImagine](minecraft.jar)
    UCHIJAAAA   AM2-Preloader{0.0.2} [AMCore](minecraft.jar)
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar)
    UCHIJAAAA   NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar)
    UCHIJAAAA   technomCore{0.12.5} [Technomancy Core](minecraft.jar)
    UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar)
    UCHIJAAAA   WitchingGadgetsCore{1.1.10} [Witching Gadgets Core](minecraft.jar)
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar)
    UCHIJAAAA   mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar)
    UCHIJAAAA   ExtendedPotions{1.2} [Extended Potions](ExtendedPotions-MC1.7.10-1.2.jar)
    UCHIJAAAA   gilded-games-util{1.7.10-1.2} [Gilded Games Utility](gilded-games-util-1.7.10-1.9.jar)
    UCHIJAAAA   dynamicswordskills{1.7.10-1.6.5} [Dynamic Sword Skills](1.7.10-dynamicswordskills-1.6.5.jar)
    UCHIJAAAA   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.2.jar)
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar)
    UCHIJAAAA   arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008.jar)
    UCHIJAAAA   mod_ecru_MapleTree{1.1.32e} [MapleTree]([1.7.10]MapleTree Forge v1.1.32e.jar)
    UCHIJAAAA   abyssalcraft{1.9.1.2} [AbyssalCraft](AbyssalCraft-1.7.10-1.9.1.2-FINAL.jar)
    UCHIJAAAA   aether{1.7.10-1.6} [Aether II](aether-1.7.10-1.6.jar)
    UCHIJAAAA   AppleCore{1.3.0} [AppleCore](AppleCore-mc1.7.10-1.3.0.jar)
    UCHIJAAAA   armourersWorkshop{1.7.10-0.38.1.98} [Armourer's Workshop](Armourers-Workshop-1.7.10-0.38.1.98.jar)
    UCHIJAAAA   plushieWrapper{0.0.0} [Plushie Wrapper](Armourers-Workshop-1.7.10-0.38.1.98.jar)
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar)
    UCHIJAAAA   Artifacts{1.1.3} [Artifacts](Artifacts-1.1.3.jar)
    UCHIJAAAA   CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar)
    UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar)
    UCHIJAAAA   Artifice{1.7.10R1.1.4} [Artifice](Artifice-1.7.10-1.1.5R-399.jar)
    UCHIJAAAA   Automagy{0.28.2} [Automagy](Automagy-1.7.10-0.28.2.jar)
    UCHIJAAAA   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar)
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania r1.8-249.jar)
    UCHIJAAAA   Avaritia{1.11} [Avaritia](Avaritia-1.11.jar)
    UCHIJAAAA   Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar)
    UCHIJAAAA   betterstorage{0.13.1.127} [BetterStorage](BetterStorage-1.7.10-0.13.1.127.jar)
    UCHIJAAAA   BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar)
    UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar)
    UCHIJAAAA   ForbiddenMagic{1.7.10-0.573} [Forbidden Magic](Forbidden Magic-1.7.10-0.573.jar)
    UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar)
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar)
    UCHIJAAAA   TConstruct{1.7.10-1.8.6b.build976} [Tinkers' Construct](TConstruct-1.7.10-1.8.6b.jar)
    UCHIJAAAA   BloodArsenal{1.2-5} [Blood Arsenal](BloodArsenal-1.7.10-1.2-5.jar)
    UCHIJAAAA   ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar)
    UCHIJAAAA   TwilightForest{2.3.5} [The Twilight Forest](twilightforest-1.7.10-2.3.5.jar)
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar)
    UCHIJAAAA   cosmeticWings{0.4.2} [Cosmetic Wings](Cosmetic-Wings-Mod-1.7.10.jar)
    UCHIJAAAA   customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar)
    UCHIJAAAA   DummyCore{1.13} [DummyCore](DummyCore1.13.jar)
    UCHIJAAAA   Dynmap{2.1-104} [Dynmap](Dynmap-2.1-forge-1.7.10.jar)
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar)
    UCHIJAAAA   EnhancedBooks{1.7.10.01} [Enhanced Books](Enhanced%20Books-1.7.10.01.jar)
    UCHIJAAAA   etfuturum{1.5.5} [Et Futurum](Et Futurum-1.5.5.jar)
    UCHIJAAAA   gadomancy{1.0.6.1} [Gadomancy](gadomancy-1.7.10-1.0.6.3.jar)
    UCHIJAAAA   godweapons{4.2} [Gods' Weapons](godweapons - 1.7.10 - 4.2.jar)
    UCHIJAAAA   GraveStone{2.16.1} [GraveStone](GraveStone-2.16.1.jar)
    UCHIJAAAA   grimoireofalice{2.1} [Grimoire of Alice](grimoireOfAlice-2.1.jar)
    UCHIJAAAA   GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](GrimoireOfGaia3-1.7.10-1.2.7.jar)
    UCHIJAAAA   HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar)
    UCHIJAAAA   hearts{1.1.1} [Heart Crystal Mod](Heart Crystal by NukeDuck [1.7.10][1.1.1].jar)
    UCHIJAAAA   Highlands{2.2.3} [Highlands](Highlands-1.7.2-v-2.2.3.jar)
    UCHIJAAAA   HardcoreQuesting{4.4.4} [Hardcore Questing Mode](HQM-The Journey-4.4.4.jar)
    UCHIJAAAA   ImmibisCore{59.1.4} [Immibis Core](immibis-core-59.1.4.jar)
    UCHIJAAAA   InventoryPets{1.4.3} [Inventory Pets](inventorypets-1.7.10-1.4.3-universal.jar)
    UCHIJAAAA   THKaguyaMod{2.91-1.7.10} [Itutu no Nandai MOD+ (Touhou Items Mod)](thKaguyaMod-1.7.10-2.91.jar)
    UCHIJAAAA   journeyToGensokyo{1.7.10-0.8.3-2} [Journey To Gensokyo](JourneyToGensokyo-1.7.10-0.8.3-2.jar)
    UCHIJAAAA   levels{r2.2.3} [Levels](Levels-r2.2.3.jar)
    UCHIJAAAA   lootbags{1.8.1} [Loot Bags](LootBags-1.7.10-1.8.1.jar)
    UCHIJAAAA   lycanitesmobs{1.11.0.1 - MC 1.7.10} [Lycanites Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   freshwatermobs{1.11.0.1 - MC 1.7.10} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   demonmobs{1.11.0.1 - MC 1.7.10} [Lycanites Demon Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   desertmobs{1.11.0.1 - MC 1.7.10} [Lycanites Desert Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   mountainmobs{1.11.0.1 - MC 1.7.10} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   junglemobs{1.11.0.1 - MC 1.7.10} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   swampmobs{1.11.0.1 - MC 1.7.10} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   shadowmobs{1.11.0.1 - MC 1.7.10} [Lycanites Shadow Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   infernomobs{1.11.0.1 - MC 1.7.10} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   saltwatermobs{1.11.0.1 - MC 1.7.10} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   forestmobs{1.11.0.1 - MC 1.7.10} [Lycanites Forest Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   plainsmobs{1.11.0.1 - MC 1.7.10} [Lycanites Plains Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   arcticmobs{1.11.0.1 - MC 1.7.10} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.11.0.1 [1.7.10].jar)
    UCHIJAAAA   magianaturalis{0.1.5b} [Magia Naturalis](MagiaNaturalis-1.7.10-0.1.5b.jar)
    UCHIJAAAA   is_mtc{1.7.8} [Mine Trading Cards](Mine Trading Cards-1.7.8.jar)
    UCHIJAAAA   Mystcraft{0.12.3.01} [Mystcraft](mystcraft-1.7.10-0.12.3.01.jar)
    UCHIJAAAA   Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar)
    UCHIJAAAA   recipehandler{1.7.10} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.3%281.7.10%29.jar)
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10j.jar)
    UCHIJAAAA   RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar)
    UCHIJAAAA   RedLogic{59.1.11} [RedLogic](redlogic-59.1.11.jar)
    UCHIJAAAA   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar)
    UCHIJAAAA   xreliquary{1.2} [Reliquary](Reliquary-1.2.jar)
    UCHIJAAAA   Roguelike{1.5.0} [Roguelike Dungeons](roguelike-1.7.10-1.5.0b.jar)
    UCHIJAAAA   rpginventorymod{1.7.2} [Rpg Inventory](RpgInventory 1.7.10 v4 base.jar)
    UCHIJAAAA   RTG{0.6.2} [Realistic Terrain Generation](RTG-1.7.10-0.6.2.jar)
    UCHIJAAAA   TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar)
    UCHIJAAAA   thaumicbases{1.3.1710.2} [Thaumic Bases](ThaumicBases-1.3.1710.4.jar)
    UCHIJAAAA   ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-53.jar)
    UCHIJAAAA   ThaumicHorizons{1.1.9} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.9.jar)
    UCHIJAAAA   alfheimwings{30} [The Wings of Alfheim](The Wings of Alfheim-1.7.10-30.jar)
    UCHIJAAAA   erebus{0.4.5} [Erebus](TheErebus-0.4.5.jar)
    UCHIJAAAA   touhou_alice_core{1.7.10-kog3} [Alice's Core MOD](TouhouAliceDoll_kog3.jar)
    UCHIJAAAA   touhou_alice_dolls{1.7.10-kog3} [Alice's Dolls MOD](TouhouAliceDoll_kog3.jar)
    UCHIJAAAA   touhou_alice_extras{1.7.10-kog3} [Alice's Dolls Ex](TouhouAliceDoll_kog3.jar)
    UCHIJAAAA   TravellersGear{1.16.6} [Traveller's Gear](TravellersGear-1.7.10-1.16.6.jar)
    UCHIJAAAA   weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar)
    UCHIJAAAA   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar)
    UCHIJAAAA   WitchingGadgets{1.1.10} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.10.jar)
    UCHIJAAAA   HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0.jar)
    UCHIJAAAA   IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.6%281%29.jar)
    UCHIJAAAA   technom{0.12.5} [Technomancy](Technomancy - 0.12.5 - 1.7.10.jar)
    CoFHCore: -[1.7.10]3.1.2-325
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
    TConstruct Environment: Environment healthy.
    Hardcore Ender Expansion: CAUTION! Ars Magica 2 is not supported by HEE, if the crash is caused by a conflict of the two mods, it will very likely not be possible to fix.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 7 / 100; [EntityPlayerMP['Zervah_Nahveron'/170751, l='Ataraxia', x=-2438.70, y=74.36, z=-1452.34](Zervah_Nahveron at -2438.7004149374147,74.36435764665791,-1452.339859613585), EntityPlayerMP['xBinketx'/253019, l='Ataraxia', x=55.45, y=75.00, z=-423.81](xBinketx at 55.448901441941366,75.0,-423.81070112986384), EntityPlayerMP['Arekkuusu'/189490, l='Ataraxia', x=752.17, y=153.00, z=656.10](Arekkuusu at 752.1707110311669,153.0,656.0990478752213), EntityPlayerMP['Naomi_Fujioka'/267739, l='DIM66', x=-2438.80, y=67.00, z=-1457.29](Naomi_Fujioka at -2438.7991070852368,67.0,-1457.286162036816), EntityPlayerMP['MonoDesbear'/241421, l='Ataraxia', x=98.17, y=65.00, z=858.65](MonoDesbear at 98.1662870653299,65.0,858.647197982156), EntityPlayerMP['Ryuu_Kurosawa'/289909, l='Ataraxia', x=-1968.50, y=64.00, z=-526.50](Ryuu_Kurosawa at -1968.5,64.0,-526.5), EntityPlayerMP['88pie'/251341, l='Ataraxia', x=-2427.97, y=67.00, z=-1434.27](88pie at -2427.9714557138295,67.0,-1434.2740367143863)]
    Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
    Type: Dedicated Server (map_server.txt)
**Error 2:** [00:53:09] [Server thread/INFO] [FML/]: Unknown net.minecraftforge.common.chunkio.QueuedChunk { x: 62 z: 8 loader: null world: DIM66 dimension: 66 provider: erebus.world.WorldProviderErebus } [00:53:09] [Server thread/INFO] [FML/]: This should not happen. Please report this error to Forge. [00:53:09] [Server thread/INFO] [FML/]: Unknown net.minecraftforge.common.chunkio.QueuedChunk { x: 62 z: 8 loader: null world: DIM66 dimension: 66 provider: erebus.world.WorldProviderErebus } [00:53:09] [Server thread/INFO] [FML/]: This should not happen. Please report this error to Forge.

**Comment by vadis365** [comment] 2016-06-13 16:25
Hello,
Could you try updating to the current version of Erebus? 0.4.7 at the time of writing this.
I pushed a fix that stopped redgem causing a decorating error in the worldgen, which could have caused your issue, a while ago. If you could update and let me know if the issue is still there.
Cheers,
Me.

**Comment by BunnyCinnamon** [comment] 2016-06-13 16:53
Oh Im so sorry, I could have sworn I was using the latest version.

**Comment by vadis365** [comment] 2016-06-13 17:20
No worries - let me know if the newer version works for you :)

**Comment by BunnyCinnamon** [comment] 2016-06-14 18:18
Yeah it works :D however now that I updated, the world is always loaded, and causes the server to run out of memory very fast. If I try to unoad the world:
http://pastebin.com/aubrhYvn

**Comment by vadis365** [comment] 2016-06-17 14:07
That is very strange as the spawner code looks like it is running - but it also shouldn't run when there are no players in the dimension. The specific line that the error points to is the one checking if there are any players in the Erebus and if there are not then do not spawn mobs.

**Comment by cubespace** [comment] 2016-12-21 13:56
I have the same problem. In the beginning of the topic, crash servers.

**Comment by vadis365** [comment] 2017-06-26 14:54
Closing - 1.7.10 is no longer supported - newer version have changed the worldgen.

**Closed as completed by vadis365** 2017-06-26 14:54 UTC
Labels: bug
