### ISSUE TITLE
[1.12.2] [1.0.22] Startup Crash with Astral Sorcery, Erebus and NEI

### ISSUE THREAD

**Issue by SassyCultist** [ganymedes01/TheErebus#624] opened 2018-06-12 23:11 UTC
This crash occured on startup and I'm not sure which mod is the exact issue. However, I think it started with the new Astral update.

https://pastebin.com/8VWwX2hf

[Astral Issue](https://github.com/HellFirePvP/AstralSorcery/issues/747)
[NEI Issue](https://github.com/TheCBProject/NotEnoughItems/issues/161)

Minecraft Forge: 14.23.4.2705
Astral Sorcery: 1.9.0
Erebus: 1.0.2332
NEI: 2.4.1.233

**Comment by SassyCultist** [comment] 2018-06-13 15:43
According to the other devs, the issue is from this mod.

**Comment by Rongmario** [comment] 2018-06-13 17:31
Happens with VanillaFoodPantry, but does not crash. https://hastebin.com/tudocazuja.swift

**Comment by vadis365** [comment] 2018-06-15 11:12
Hello,
Of course it is, that is a standard response by any modder when something weird crops up that has no immediate or obvious reason and possibly false positives in the stacktrace :P 
Saying that, the cause may well be Erebus, but it is unusual that other mods cause the exact same crash when Erebus isn't present. I'll look in to it and see if it is Erebus breaking all the things \o/
Cheers,
Me.

**Comment by kotoroshinoto** [comment] 2018-06-16 05:15
I am experiencing the same issue.

It LOOKS like it has something to do with the result returned by erebus.items.ItemErebusFood.getItemStackLimit(ItemErebusFood.java:138

which in turn apparently called erebus.items.ItemErebusFood.hasContainerItem(ItemErebusFood.java:133)

which called erebus.items.ItemErebusFood.getContainerItem(ItemErebusFood.java:116)

but why that line in ItemErebusFood.java (116) would throw java.lang.ArrayIndexOutOfBoundsException: 32767 is not immediately obvious to me. as that line appears to be returning an itemstack of Items.BOWL

**Comment by PocketfulOfGeese** [comment] 2018-06-16 12:09
There's reports that Erebus 1.0.22 is only seeing this crash with AS 1.9.0 with Custom NPCs installed causing the trace to push other mods up on calling that result.

**Comment by SassyCultist** [comment] 2018-06-16 12:49
I do not have Custom NPCs installed.

**Comment by kotoroshinoto** [comment] 2018-06-17 00:21
I do not either

**Comment by PocketfulOfGeese** [comment] 2018-06-17 02:29
Guess that rules that out as conflicting reports, then

**Comment by HellFirePvP** [comment] 2018-06-18 13:28
https://github.com/ganymedes01/TheErebus/blob/mc1.9/src/main/java/erebus/items/ItemErebusFood.java#L112

The one line in almost the entire class that does not check for out-of-bounds calls such as wildcards and that being the culprit here.

**Comment by Shahelion** [comment] 2018-07-19 22:51
Any word on this?

**Comment by vadis365** [comment] 2018-07-25 16:31
Fixed in dev.
Closing as the next release will have this sorted.

**Closed as completed by vadis365** 2018-07-25 16:31 UTC
